# -*- coding: utf-8 -*-
"""Kedai Kasut

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17XFhtFM-F2IONDW4eSiEd2l6YiA0CDZp
"""

from collections import Counter

# Input 1
num_of_shoes = int(input('Enter amount of shoes available: '))

while num_of_shoes < 0 or num_of_shoes > 10**3:
    print("Invalid input entered!")
    num_of_shoes = int(input('Enter amount of shoes available: '))

# Input 2
shoe_list = input('List all of shoes in store: ')

# Input 3
num_of_customer = int(input("Enter number of customer: "))

list_of_order = []

# Input 4
for i in range(0, num_of_customer):
  order = input('Enter shoes size and offered prize: ')
  list_of_order.append(order)

shoe_list = list(shoe_list.split())

shoe_stock = dict(Counter(shoe_list))

def check_shoes(size):
  try:
    if shoe_stock[size] != 0:
      available = True
    else:
      available = False

    
  except:
    available = False

  return available

def update_stock(size):
  shoe_stock[size] = shoe_stock[size] - 1

total = 0

for i in list_of_order:
  #total = 0
  order = i.split()
  size = order[0]
  #print(size)
  offer = order[1]
  #print(offer)

  available = check_shoes(size)

  #print(available)

  if available:
    update_stock(size)
    total = total + int(offer)
    #print('total = ', total)

print(total)

